complexity:
  LongParameterList:
    functionThreshold: 25
    ignoreDefaultParameters: true

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  FunctionNaming:
    functionPattern: '([A-Za-z][a-zA-Z0-9]*)|(`.*`)'

style:
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
